# Test against this version of node.js
version: 1.0.{build}
build:
  verbosity: minimal
  
environment:
  matrix:
    # node.js
    - nodejs_version: "6"

    # Install scripts. (run after repo cloning)
    install: install-product node $env:nodejs_version
      #Get the latest stable version of Node.js or io.js
      #- ps: 
      # install modules
      - npm install

    # Post-install test script.
    test_script:
       # Output useful info for debugging.
      - node --version
      - npm --version

       # run tests
      - npm test

    # Don't actually build
    build: off

